# encoding: utf-8

DC = ENV['DC'] || 'ldc'

DOKYO_API = Dir.glob('../dokyo/*.d').map do |path|
  path.gsub(/\.d$/, '.o').tap { |a| p a }
end

EXAMPLES = [
  'HashDatabaseExample'
]

rule '.o' => [ '.d' ] do |t|
  sh "#{DC} #{t.source} -I=.. -I=../dokyo -c -of=#{t.name}"
end

EXAMPLES.each do |example|
  deps = DOKYO_API + [ "#{example}.o" ]
  desc "Build '#{example}' Demo"
  task({example => deps}) do |t|
    prerequisites = t.prerequisites.join(' ')
    sh "#{DC} #{prerequisites} -L-ltokyocabinet -of=#{example}"
  end
end

desc 'Build all Demos'
task :all => EXAMPLES

desc 'Cleanup'
task :clean do
  [ '**/*.~*', '**/*.o', *EXAMPLES, *DOKYO_API ].each do |mask|
    Dir.glob(mask) { |path| rm_f(path) }
  end
end

task :default => :all
