# encoding: utf-8

DC = ENV['DC'] || 'ldc'

task :default => :build

rule '.o' => [ '.d' ] do |t|
  sh "#{DC} #{t.source} -I=.. -I=../dokyo -c -of=#{t.name}"
end

task :build_tch => [ 'dokyo_tch.o' ] do |t|
  prerequisites = t.prerequisites.join(' ')
  sh "#{DC} #{prerequisites} -L-ltokyocabinet -of=dokyo_tch"
end

task :build_oop_tch => [ 'dokyo_oop_tch.o',
                         '../dokyo/HashDatabase.o' ] do |t|
  prerequisites = t.prerequisites.join(' ')
  sh "#{DC} #{prerequisites} -L-ltokyocabinet -of=dokyo_oop_tch"
end

task :build => [ 'build_tch', 'build_oop_tch' ]

task :clean do
  cleaner = proc { |path| rm_f(path) }

  Dir.glob('**/*.~*', &cleaner)
  Dir.glob('**/*.o', &cleaner)
  Dir.glob('dokyo_tch', &cleaner)
  Dir.glob('dokyo_oop_tch', &cleaner)
end
